### ISSUE TITLE
关于Server端的一系列问题

### ISSUE THREAD

**Issue by Jack-Myth** [qiuhaotc/CodeIndex#15]
这个Server可以放在某个公共的服务器上供多人使用吗？
如果放在公共的服务器上，会产生什么性能问题吗？
如果可以多人共用，那多人用同一个项目是否还需要重新生成索引？

**Comment by Jack-Myth** [comment]
因为每个人的电脑上项目路径是不一样的，不知道CodeIndex有没有做什么处理？

**Comment by qiuhaotc** [comment]
> 这个Server可以放在某个公共的服务器上供多人使用吗？ 如果放在公共的服务器上，会产生什么性能问题吗？ 如果可以多人共用，那多人用同一个项目是否还需要重新生成索引？

1. 可以放在公共端使用, 需要使用的电脑可以开放远程访问, 就可以进行索引. 或者公共服务器索引自己的文件
2. 性能影响不大, 除非索引文件非常大或者索引目录非常多
3. 同一个项目如果每个人路径不一样, 最好重新生成索引, 因为每个人改动不一样, 还可以通过配置mapping来mapping到本地的文件系统

**Comment by Jack-Myth** [comment]
“配置Mapping”这个功能好像没有看见有什么说明？

**Comment by qiuhaotc** [comment]
> “配置Mapping”这个功能好像没有看见有什么说明？

原来是给docker用的 docker使用的是虚拟文件路径 需要映射到外部的实际路径 
例如 user\somebody\index, mapping 到 D:\CodeIndex

**Comment by Jack-Myth** [comment]
好的，我知道了，谢谢
